### ISSUE TITLE
https://freemobilenetstat.appspot.com/ is 404

### ISSUE THREAD

**Issue by ghost** [gilbsgilbs/freemobilenetstat#34]
@gilbsgilbs 
* https://freemobilenetstat.appspot.com/ is error 404
* did it moved permanently or changed domain name?

**Comment by gilbsgilbs** [comment]
Hi, thanks for raising an issue. I think we can consider that this project is dead (unless someone wants to work on it again). It should be archived.

**Comment by ghost** [comment]
updated as part of https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13560
* thank you
